name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v3

    - name: EC2에 접속해서 배포하기
      run: |
        echo "${{ secrets.PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@서버주소 << EOF
          cd /home/ec2-user/my-app
          git pull origin main
          npm run build
          pm2 restart all
        EOF
